USB_VID = 0x1209
USB_PID = 0x9000
USB_PRODUCT = "CanSat v1"
USB_MANUFACTURER = "GreeniusGenius"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2


EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ" #Stacked Winbond flash on RP2354B

#FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel/

CIRCUITPY_USB_HOST = 0

#CIRCUITPY__EVE = 1
